package db

import "encoding/binary"

// uint64Bytes encodes a uint64 value into an 8-byte little-endian byte slice.
// This is used to serialize document IDs (generated by bbolt's bucket sequence)
// into byte keys suitable for storage as bbolt bucket keys.
//
// Little-endian encoding is chosen for consistency; note that bbolt's default
// cursor ordering is lexicographic over raw bytes, so little-endian keys do
// NOT sort numerically. If ordered iteration by ID is required in the future,
// big-endian encoding would be the appropriate choice.
func uint64Bytes(n uint64) []byte {
	b := make([]byte, 8)
	binary.LittleEndian.PutUint64(b, n)
	return b
}

// uint64FromBytes decodes an 8-byte little-endian byte slice back into a
// uint64. This is the inverse of uint64Bytes and is used when reading document
// keys from bbolt to reconstruct the numeric ID for inclusion in query results.
func uint64FromBytes(b []byte) uint64 {
	return binary.LittleEndian.Uint64(b)
}
